package opensettle

import (
	"context"
	"errors"
	"net/http"
	"strings"
	"testing"
	"time"
)

func TestHTTP_AuthorizationHeader(t *testing.T) {
	s := newStubServer()
	defer s.Close()
	c := newTestClient(t, s)
	s.queue(200, `{"id":"cu_1"}`)
	_, _ = c.Customers.Retrieve(bgCtx(), "cu_1")
	got := s.lastRequest(t).Headers.Get("Authorization")
	if got != "Bearer sk_test_unit" {
		t.Fatalf("got %q", got)
	}
}

func TestHTTP_UserAgentHeader(t *testing.T) {
	s := newStubServer()
	defer s.Close()
	c := newTestClient(t, s)
	s.queue(200, `{"id":"cu_1"}`)
	_, _ = c.Customers.Retrieve(bgCtx(), "cu_1")
	got := s.lastRequest(t).Headers.Get("User-Agent")
	if !strings.HasPrefix(got, "opensettle-go/") {
		t.Fatalf("got %q", got)
	}
}

func TestHTTP_AcceptHeader(t *testing.T) {
	s := newStubServer()
	defer s.Close()
	c := newTestClient(t, s)
	s.queue(200, `{"id":"cu_1"}`)
	_, _ = c.Customers.Retrieve(bgCtx(), "cu_1")
	if got := s.lastRequest(t).Headers.Get("Accept"); got != "application/json" {
		t.Fatalf("got %q", got)
	}
}

func TestHTTP_ContentTypeOnPost(t *testing.T) {
	s := newStubServer()
	defer s.Close()
	c := newTestClient(t, s)
	s.queue(200, `{"id":"cu_1","workspaceId":"ws","email":"a@b","name":"","status":"active","activeSubscriptions":0,"lifetimeValue":0,"createdAt":""}`)
	_, _ = c.Customers.Create(bgCtx(), CreateCustomerRequest{Email: "a@b"})
	got := s.lastRequest(t).Headers.Get("Content-Type")
	if got != "application/json" {
		t.Fatalf("got %q", got)
	}
}

func TestHTTP_ContentTypeAbsentOnGet(t *testing.T) {
	s := newStubServer()
	defer s.Close()
	c := newTestClient(t, s)
	s.queue(200, `{"id":"cu_1"}`)
	_, _ = c.Customers.Retrieve(bgCtx(), "cu_1")
	if got := s.lastRequest(t).Headers.Get("Content-Type"); got != "" {
		t.Fatalf("got %q", got)
	}
}

func TestHTTP_IdempotencyKeyAutoGenerated(t *testing.T) {
	s := newStubServer()
	defer s.Close()
	c := newTestClient(t, s)
	s.queue(200, `{"id":"cu_1"}`)
	_, _ = c.Customers.Create(bgCtx(), CreateCustomerRequest{Email: "a@b"})
	got := s.lastRequest(t).Headers.Get("Idempotency-Key")
	if got != "test-idem-key" {
		t.Fatalf("got %q", got)
	}
}

func TestHTTP_IdempotencyKeyAbsentOnGET(t *testing.T) {
	s := newStubServer()
	defer s.Close()
	c := newTestClient(t, s)
	s.queue(200, `{"id":"cu_1"}`)
	_, _ = c.Customers.Retrieve(bgCtx(), "cu_1")
	if got := s.lastRequest(t).Headers.Get("Idempotency-Key"); got != "" {
		t.Fatalf("got %q", got)
	}
}

func TestHTTP_WorkspaceURLPrefix(t *testing.T) {
	s := newStubServer()
	defer s.Close()
	c := newTestClient(t, s)
	s.queue(200, `{"id":"cu_1"}`)
	_, _ = c.Customers.Retrieve(bgCtx(), "cu_1")
	got := s.lastRequest(t).Path
	if got != "/v1/workspaces/ws_test/customers/cu_1" {
		t.Fatalf("got %q", got)
	}
}

func TestHTTP_WorkspaceIDIsPathEscaped(t *testing.T) {
	s := newStubServer()
	defer s.Close()
	c, err := NewClient("sk_test_unit", "ws with space",
		WithBaseURL(s.server.URL),
		WithMaxRetries(0),
	)
	if err != nil {
		t.Fatal(err)
	}
	c.http.sleep = func(time.Duration) {}
	s.queue(200, `{"id":"cu_1"}`)
	_, _ = c.Customers.Retrieve(bgCtx(), "cu_1")
	got := s.lastRequest(t).RawPath
	if !strings.Contains(got, "/workspaces/ws%20with%20space/") {
		t.Fatalf("got %q", got)
	}
}

func TestHTTP_BaseURLTrailingSlashStripped(t *testing.T) {
	s := newStubServer()
	defer s.Close()
	c, err := NewClient("sk_test_x", "ws_x",
		WithBaseURL(s.server.URL+"/"),
		WithMaxRetries(0),
	)
	if err != nil {
		t.Fatal(err)
	}
	c.http.sleep = func(time.Duration) {}
	s.queue(200, `{"id":"cu_1"}`)
	_, _ = c.Customers.Retrieve(bgCtx(), "cu_1")
	got := s.lastRequest(t).Path
	if got != "/v1/workspaces/ws_x/customers/cu_1" {
		t.Fatalf("got %q", got)
	}
}

func TestHTTP_QueryString(t *testing.T) {
	s := newStubServer()
	defer s.Close()
	c := newTestClient(t, s)
	s.queue(200, `{"data":[],"nextCursor":""}`)
	_, _ = c.Customers.List(bgCtx(), &ListCustomersQuery{Cursor: "cur_1", Limit: 25, Status: CustomerActive})
	got := s.lastRequest(t).Query
	if !strings.Contains(got, "cursor=cur_1") || !strings.Contains(got, "limit=25") || !strings.Contains(got, "status=active") {
		t.Fatalf("got %q", got)
	}
}

func TestHTTP_QueryStringEmpty(t *testing.T) {
	s := newStubServer()
	defer s.Close()
	c := newTestClient(t, s)
	s.queue(200, `{"data":[],"nextCursor":""}`)
	_, _ = c.Customers.List(bgCtx(), nil)
	got := s.lastRequest(t).Query
	if got != "" {
		t.Fatalf("got %q", got)
	}
}

func TestHTTP_QueryStringDropsEmpty(t *testing.T) {
	s := newStubServer()
	defer s.Close()
	c := newTestClient(t, s)
	s.queue(200, `{"data":[],"nextCursor":""}`)
	_, _ = c.Customers.List(bgCtx(), &ListCustomersQuery{Cursor: "", Limit: 0})
	got := s.lastRequest(t).Query
	if got != "" {
		t.Fatalf("got %q", got)
	}
}

func TestHTTP_204NoContent(t *testing.T) {
	s := newStubServer()
	defer s.Close()
	c := newTestClient(t, s)
	s.queue(204, "")
	if err := c.Customers.Delete(bgCtx(), "cu_1"); err != nil {
		t.Fatalf("got %v", err)
	}
}

func TestHTTP_200EmptyBody(t *testing.T) {
	s := newStubServer()
	defer s.Close()
	c := newTestClient(t, s)
	s.queue(200, "")
	if err := c.Customers.Delete(bgCtx(), "cu_1"); err != nil {
		t.Fatalf("got %v", err)
	}
}

func TestHTTP_RetryOn500(t *testing.T) {
	s := newStubServer()
	defer s.Close()
	c := newTestClient(t, s)
	c = withRetries(c, 2)
	s.queue(500, `{"error":{"code":"internal_error","message":"oops"}}`)
	s.queue(200, `{"id":"cu_1"}`)
	_, err := c.Customers.Retrieve(bgCtx(), "cu_1")
	if err != nil {
		t.Fatalf("got %v", err)
	}
	if len(s.requests) != 2 {
		t.Fatalf("expected 2 requests, got %d", len(s.requests))
	}
}

func TestHTTP_RetryOn429RespectsRetryAfter(t *testing.T) {
	s := newStubServer()
	defer s.Close()
	c := newTestClient(t, s)
	c = withRetries(c, 1)
	s.queueWith(cannedResponse{
		Status:  429,
		Body:    `{"error":{"code":"rate_limited","message":"slow"}}`,
		Headers: map[string]string{"Retry-After": "2"},
	})
	s.queue(200, `{"id":"cu_1"}`)
	_, err := c.Customers.Retrieve(bgCtx(), "cu_1")
	if err != nil {
		t.Fatalf("got %v", err)
	}
	if len(s.requests) != 2 {
		t.Fatalf("got %d requests", len(s.requests))
	}
}

func TestHTTP_NoRetryOn400(t *testing.T) {
	s := newStubServer()
	defer s.Close()
	c := newTestClient(t, s)
	c = withRetries(c, 3)
	s.queue(400, `{"error":{"code":"invalid_request","message":"bad"}}`)
	_, err := c.Customers.Retrieve(bgCtx(), "cu_1")
	if err == nil {
		t.Fatal("expected error")
	}
	if len(s.requests) != 1 {
		t.Fatalf("got %d requests", len(s.requests))
	}
}

func TestHTTP_NoRetryOn404(t *testing.T) {
	s := newStubServer()
	defer s.Close()
	c := newTestClient(t, s)
	c = withRetries(c, 3)
	s.queue(404, `{"error":{"code":"not_found","message":"x"}}`)
	_, err := c.Customers.Retrieve(bgCtx(), "cu_1")
	if err == nil {
		t.Fatal("expected error")
	}
	if len(s.requests) != 1 {
		t.Fatalf("got %d requests", len(s.requests))
	}
}

func TestHTTP_RetryBudgetExhausted(t *testing.T) {
	s := newStubServer()
	defer s.Close()
	c := newTestClient(t, s)
	c = withRetries(c, 2)
	s.queue(503, `{"error":{"code":"internal_error","message":"down"}}`)
	s.queue(503, `{"error":{"code":"internal_error","message":"down"}}`)
	s.queue(503, `{"error":{"code":"internal_error","message":"down"}}`)
	_, err := c.Customers.Retrieve(bgCtx(), "cu_1")
	if err == nil {
		t.Fatal("expected error")
	}
	if len(s.requests) != 3 {
		t.Fatalf("got %d requests", len(s.requests))
	}
}

func TestHTTP_RetryNetworkError(t *testing.T) {
	// Build a client pointing at a closed port (immediate connection error)
	// to exercise the network-error retry path.
	s := newStubServer()
	addr := s.server.URL
	s.Close()
	c, err := NewClient("sk_test_x", "ws_x", WithBaseURL(addr), WithMaxRetries(2))
	if err != nil {
		t.Fatal(err)
	}
	c.http.sleep = func(time.Duration) {}
	_, err = c.Customers.Retrieve(bgCtx(), "cu_1")
	var netErr *NetworkError
	if !errors.As(err, &netErr) {
		t.Fatalf("got %T", err)
	}
}

func TestHTTP_ContextCanceled(t *testing.T) {
	s := newStubServer()
	defer s.Close()
	c := newTestClient(t, s)
	ctx, cancel := context.WithCancel(bgCtx())
	cancel()
	_, err := c.Customers.Retrieve(ctx, "cu_1")
	if err == nil {
		t.Fatal("expected error")
	}
}

func TestHTTP_ServerReturnsNonJSONOn200(t *testing.T) {
	s := newStubServer()
	defer s.Close()
	c := newTestClient(t, s)
	s.queue(200, "<html>")
	_, err := c.Customers.Retrieve(bgCtx(), "cu_1")
	var apiErr *APIError
	if !errors.As(err, &apiErr) {
		t.Fatalf("got %T: %v", err, err)
	}
}

func TestHTTP_RequestBodyEncoded(t *testing.T) {
	s := newStubServer()
	defer s.Close()
	c := newTestClient(t, s)
	s.queue(200, `{"id":"cu_1","workspaceId":"ws","email":"x@y","name":"X","status":"active","activeSubscriptions":0,"lifetimeValue":0,"createdAt":""}`)
	_, _ = c.Customers.Create(bgCtx(), CreateCustomerRequest{Email: "x@y", Name: "X"})
	body := decodeBody[map[string]any](t, s.lastRequest(t).Body)
	if body["email"] != "x@y" || body["name"] != "X" {
		t.Fatalf("got %#v", body)
	}
}

func TestParseRetryAfter_Numeric(t *testing.T) {
	if got := parseRetryAfter("42", time.Now()); got != 42 {
		t.Fatalf("got %v", got)
	}
}

func TestParseRetryAfter_FractionalNumeric(t *testing.T) {
	if got := parseRetryAfter("0.5", time.Now()); got != 0.5 {
		t.Fatalf("got %v", got)
	}
}

func TestParseRetryAfter_NegativeIsZero(t *testing.T) {
	if got := parseRetryAfter("-5", time.Now()); got != 0 {
		t.Fatalf("got %v", got)
	}
}

func TestParseRetryAfter_HTTPDate(t *testing.T) {
	future := time.Now().Add(10 * time.Second).UTC().Format(http.TimeFormat)
	got := parseRetryAfter(future, time.Now())
	if got < 8 || got > 11 {
		t.Fatalf("got %v", got)
	}
}

func TestParseRetryAfter_PastHTTPDate(t *testing.T) {
	past := time.Now().Add(-10 * time.Second).UTC().Format(http.TimeFormat)
	got := parseRetryAfter(past, time.Now())
	if got != 0 {
		t.Fatalf("got %v", got)
	}
}

func TestParseRetryAfter_Garbage(t *testing.T) {
	if got := parseRetryAfter("not-a-thing", time.Now()); got != 0 {
		t.Fatalf("got %v", got)
	}
}

func TestParseRetryAfter_Empty(t *testing.T) {
	if got := parseRetryAfter("", time.Now()); got != 0 {
		t.Fatalf("got %v", got)
	}
}

func TestBackoffFor_ExponentialCap(t *testing.T) {
	// 250ms * 2^attempt, capped at 4s. attempts 0..4 should yield
	// 250ms, 500ms, 1s, 2s, 4s; attempt 5 also caps at 4s.
	cases := []struct {
		attempt int
		want    time.Duration
	}{
		{0, 250 * time.Millisecond},
		{1, 500 * time.Millisecond},
		{2, 1 * time.Second},
		{3, 2 * time.Second},
		{4, 4 * time.Second},
		{5, 4 * time.Second},
		{6, 4 * time.Second},
	}
	for _, tc := range cases {
		if got := backoffFor(tc.attempt, 0); got != tc.want {
			t.Errorf("attempt=%d: got %v, want %v", tc.attempt, got, tc.want)
		}
	}
}

func TestBackoffFor_RetryAfterOverrides(t *testing.T) {
	if got := backoffFor(0, 3); got != 3*time.Second {
		t.Fatalf("got %v", got)
	}
}

func TestEncodeQuery_Deterministic(t *testing.T) {
	a := encodeQuery(map[string]any{"b": "2", "a": "1"})
	b := encodeQuery(map[string]any{"a": "1", "b": "2"})
	if a != b {
		t.Fatalf("not deterministic: %q vs %q", a, b)
	}
	if a != "a=1&b=2" {
		t.Fatalf("got %q", a)
	}
}

func TestEncodeQuery_Bool(t *testing.T) {
	if got := encodeQuery(map[string]any{"active": true}); got != "active=true" {
		t.Fatalf("got %q", got)
	}
}

func TestEncodeQuery_Int(t *testing.T) {
	if got := encodeQuery(map[string]any{"limit": 25}); got != "limit=25" {
		t.Fatalf("got %q", got)
	}
}

func TestEncodeQuery_NilValueDropped(t *testing.T) {
	if got := encodeQuery(map[string]any{"x": nil, "y": "1"}); got != "y=1" {
		t.Fatalf("got %q", got)
	}
}

func TestEncodeQuery_EmptyStringDropped(t *testing.T) {
	if got := encodeQuery(map[string]any{"x": "", "y": "1"}); got != "y=1" {
		t.Fatalf("got %q", got)
	}
}

func TestEncodeQuery_EmptyMap(t *testing.T) {
	if got := encodeQuery(map[string]any{}); got != "" {
		t.Fatalf("got %q", got)
	}
}

func TestEncodeQuery_Nil(t *testing.T) {
	if got := encodeQuery(nil); got != "" {
		t.Fatalf("got %q", got)
	}
}

func TestGenerateIdempotencyKey_UUIDFormat(t *testing.T) {
	k := generateIdempotencyKey()
	if len(k) != 36 {
		t.Fatalf("len %d: %q", len(k), k)
	}
	if k[8] != '-' || k[13] != '-' || k[18] != '-' || k[23] != '-' {
		t.Fatalf("bad dashes: %q", k)
	}
	// version 4 nibble
	if k[14] != '4' {
		t.Fatalf("not v4: %q", k)
	}
	v := k[19]
	if v != '8' && v != '9' && v != 'a' && v != 'b' {
		t.Fatalf("bad variant: %q", k)
	}
}

func TestGenerateIdempotencyKey_Unique(t *testing.T) {
	a := generateIdempotencyKey()
	b := generateIdempotencyKey()
	if a == b {
		t.Fatalf("not unique: %q vs %q", a, b)
	}
}

func TestHTTP_QueryParamPathEscape(t *testing.T) {
	s := newStubServer()
	defer s.Close()
	c := newTestClient(t, s)
	s.queue(200, `{"data":[],"nextCursor":""}`)
	_, _ = c.Customers.List(bgCtx(), &ListCustomersQuery{Q: "a b&c"})
	got := s.lastRequest(t).Query
	if !strings.Contains(got, "q=a+b%26c") {
		t.Fatalf("got %q", got)
	}
}

func TestHTTP_CustomerIDInPathEscaped(t *testing.T) {
	s := newStubServer()
	defer s.Close()
	c := newTestClient(t, s)
	s.queue(200, `{"id":"x"}`)
	_, _ = c.Customers.Retrieve(bgCtx(), "cu/with/slash")
	got := s.lastRequest(t).RawPath
	if !strings.Contains(got, "cu%2Fwith%2Fslash") {
		t.Fatalf("got %q", got)
	}
}

func TestHTTP_404SurfacesAsNotFoundError(t *testing.T) {
	s := newStubServer()
	defer s.Close()
	c := newTestClient(t, s)
	s.queue(404, `{"error":{"code":"not_found","message":"gone"}}`)
	_, err := c.Customers.Retrieve(bgCtx(), "cu_1")
	var target *NotFoundError
	if !errors.As(err, &target) {
		t.Fatalf("got %T", err)
	}
}

func TestHTTP_401SurfacesAsAuthError(t *testing.T) {
	s := newStubServer()
	defer s.Close()
	c := newTestClient(t, s)
	s.queue(401, `{"error":{"code":"unauthorized","message":"no"}}`)
	_, err := c.Customers.Retrieve(bgCtx(), "cu_1")
	var target *AuthenticationError
	if !errors.As(err, &target) {
		t.Fatalf("got %T", err)
	}
}

func TestHTTP_403SurfacesAsForbidden(t *testing.T) {
	s := newStubServer()
	defer s.Close()
	c := newTestClient(t, s)
	s.queue(403, `{"error":{"code":"forbidden","message":"no"}}`)
	_, err := c.Customers.Retrieve(bgCtx(), "cu_1")
	var target *ForbiddenError
	if !errors.As(err, &target) {
		t.Fatalf("got %T", err)
	}
}

func TestHTTP_AALSurfacesAsStepUp(t *testing.T) {
	s := newStubServer()
	defer s.Close()
	c := newTestClient(t, s)
	s.queue(401, `{"error":{"code":"aal_required","message":"step up"}}`)
	_, err := c.Customers.Retrieve(bgCtx(), "cu_1")
	var target *StepUpRequiredError
	if !errors.As(err, &target) {
		t.Fatalf("got %T", err)
	}
}

func TestHTTP_429SurfacesAsRateLimitWithRetryAfter(t *testing.T) {
	s := newStubServer()
	defer s.Close()
	c := newTestClient(t, s)
	s.queueWith(cannedResponse{
		Status:  429,
		Body:    `{"error":{"code":"rate_limited","message":"slow"}}`,
		Headers: map[string]string{"Retry-After": "7"},
	})
	_, err := c.Customers.Retrieve(bgCtx(), "cu_1")
	var target *RateLimitError
	if !errors.As(err, &target) {
		t.Fatalf("got %T", err)
	}
	if target.RetryAfter != 7 {
		t.Fatalf("retryAfter: %v", target.RetryAfter)
	}
}

func TestHTTP_408IsRetriable(t *testing.T) {
	s := newStubServer()
	defer s.Close()
	c := newTestClient(t, s)
	c = withRetries(c, 1)
	s.queue(408, `{"error":{"code":"internal_error","message":"timeout"}}`)
	s.queue(200, `{"id":"cu_1"}`)
	_, err := c.Customers.Retrieve(bgCtx(), "cu_1")
	if err != nil {
		t.Fatalf("got %v", err)
	}
	if len(s.requests) != 2 {
		t.Fatalf("got %d requests", len(s.requests))
	}
}

func TestHTTP_502IsRetriable(t *testing.T) {
	s := newStubServer()
	defer s.Close()
	c := newTestClient(t, s)
	c = withRetries(c, 1)
	s.queue(502, "")
	s.queue(200, `{"id":"cu_1"}`)
	_, err := c.Customers.Retrieve(bgCtx(), "cu_1")
	if err != nil {
		t.Fatalf("got %v", err)
	}
}

func TestHTTP_504IsRetriable(t *testing.T) {
	s := newStubServer()
	defer s.Close()
	c := newTestClient(t, s)
	c = withRetries(c, 1)
	s.queue(504, "")
	s.queue(200, `{"id":"cu_1"}`)
	_, err := c.Customers.Retrieve(bgCtx(), "cu_1")
	if err != nil {
		t.Fatalf("got %v", err)
	}
}

func TestHTTP_409IsNotRetriable(t *testing.T) {
	s := newStubServer()
	defer s.Close()
	c := newTestClient(t, s)
	c = withRetries(c, 3)
	s.queue(409, `{"error":{"code":"conflict","message":"dup"}}`)
	_, err := c.Customers.Retrieve(bgCtx(), "cu_1")
	if err == nil {
		t.Fatal()
	}
	if len(s.requests) != 1 {
		t.Fatalf("got %d", len(s.requests))
	}
}

func TestHTTP_DeleteSendsNoBody(t *testing.T) {
	s := newStubServer()
	defer s.Close()
	c := newTestClient(t, s)
	s.queue(204, "")
	_ = c.Customers.Delete(bgCtx(), "cu_1")
	body := s.lastRequest(t).Body
	if len(body) != 0 {
		t.Fatalf("body should be empty, got %q", body)
	}
}

func TestHTTP_PATCHMethod(t *testing.T) {
	s := newStubServer()
	defer s.Close()
	c := newTestClient(t, s)
	s.queue(200, `{"id":"cu_1","workspaceId":"ws","email":"a@b","name":"","status":"active","activeSubscriptions":0,"lifetimeValue":0,"createdAt":""}`)
	name := "new"
	_, _ = c.Customers.Update(bgCtx(), "cu_1", UpdateCustomerRequest{Name: &name})
	if got := s.lastRequest(t).Method; got != http.MethodPatch {
		t.Fatalf("got %q", got)
	}
}

func TestHTTP_RequestIDPropagatesToError(t *testing.T) {
	s := newStubServer()
	defer s.Close()
	c := newTestClient(t, s)
	s.queue(404, `{"error":{"code":"not_found","message":"x","request_id":"req_zz"}}`)
	_, err := c.Customers.Retrieve(bgCtx(), "cu_1")
	var target *NotFoundError
	if !errors.As(err, &target) {
		t.Fatal()
	}
	if target.RequestID != "req_zz" {
		t.Fatalf("got %q", target.RequestID)
	}
}
